### ISSUE TITLE
Discussion: Make UCX/UCC required instead of optional?

### ISSUE THREAD

**Issue by leofang** [conda-forge/openmpi-feedstock#181]
xref: https://github.com/conda-forge/openmpi-feedstock/pull/175#issuecomment-2378161158

**Comment by j34ni** [comment]
Why not offer two packages with explicit names: 
1- `openmpi-ofi` (which would also be the current default `openmpi`)
and
2- `openmpi-ucx`
so that users can explicitly select what they want (if they know what they are doing) and continue to use the default `ofi` if they do not care about the communication layers?

**Comment by dalcinl** [comment]
Rather than two names, I think the proper way to do it is to build two variants with a ofi vs ucx tag in the build string.

**Comment by j34ni** [comment]
How about something similar to what I did for https://github.com/conda-forge/mvapich-feedstock/blob/main/recipe using `conda_build_config.yaml` and `device = ucx` or `device = ofi`:

```
# Support for ch4:ucx or ch4:ofi devices
build_with_device=""
if [ "$device" == "ucx" ]; then
    echo "Build with UCX support"
    build_with_device=" --with-device=ch4:ucx --with-ucx=$PREFIX "
else
    echo "Build with OFI support"
    build_with_device=" --with-device=ch4:ofi "
fi

./configure --prefix=$PREFIX \
            $build_with_device \
            [...]
```
Then the user selects either the OFI version using `conda install conda-forge::openmpi=*=*_ofi`, or the UCX version with `conda install conda-forge::openmpi=*=*_ucx` without having to further activate or deactivate anything

That seems to work well

**Comment by dalcinl** [comment]
@j34ni What you are proposing is OK given the limitations (w.r.t dependencies) of MPICH and derivatives. However, you are completely ignoring @minrk's very fine points.

@minrk @leofang This is going to sound a bit silly, but what if we output trivial packages `openmpi-ucx` and `openmpi-ofi`, each depending on the core `openmpi` package, but just providing custom `$PREFIX/etc/openmpi-mca-params.conf` files with any setup required to make UCX vs. OFI the default backend?

**Comment by j34ni** [comment]
I am not ignoring what @minrk  wrote, I support the two builds approach with selection of ofi/ucx via build string

**Comment by dalcinl** [comment]
> I am not ignoring what [@minrk](https://github.com/minrk) wrote,

Well, I somehow assumed that @minrk's "Con two builds" would have been compelling enough to discourage you from what you ended up proposing.

**Comment by minrk** [comment]
Do folks have opinions here? Thank you @j34ni for chiming in in support of two separate builds (I do think we need metapackages as selectors, not just build strings, but separate builds is definitely workable). The almost-empty `openmpi-ucx/ofi` packages should work for this, and we could do the same for mvapich/mpich. I'm not sure about writing a config file unless that config file is _only_ in these packages, not the base `openmpi` due to clobber issues. An alternative is to set an env variable on activation.

Since these all support simultaneous support for multiple devices, my inclination is one build with required dependencies on all implementations (i.e. the mpich PR: https://github.com/conda-forge/mpich-feedstock/pull/100). That's fewer builds, more flexible environments, simpler installation and only a runtime choice via standard env/config/cli/etc. to pick a device.

**Comment by dalcinl** [comment]
@minrk @leofang If we want to distribute MPICH with OFI+UCX, then perhaps the simplest option is to change things here in the Open MPI recipe to (like conda-forge/mpich-feedstock#104) build a single package that depends on everything, and it is the user who decides over the OFI vs UCX backend  without having to install anything extra.

In the particular case of Open MPI, that would also allow to move our recipe to be more in line with upstream defaults, that is, remove the configure option `--enable-mca-dso` and this way the MPI library will will link to everything needed.

One minor thing to decide is what should be the default backend for Open MPI. I'm inclined to prefer whatever upstream OMPI picks, but we have to weigh in the possible issues of defaulting to UCX in the current version. For similar reasons, in the case of MPICH, I would keep using OFI as the default for the current version, though I have no problem with switching to UCX as default in the next (either minor or patch) release.

I'm also thinking whether we should eventually create a new recipe for libfabric, and then use that package as a dependency for  MPICH, MVAPICH, and Open MPI.

**Comment by j34ni** [comment]
I started to work on the recipe for libfabric

**Comment by dalcinl** [comment]
I'll sketch an update for Open MPI to depend unconditionally on UCX.

**Comment by minrk** [comment]
@j34ni that's terrific! It will actually be relevant for Intel MPI on Windows as well (https://github.com/conda-forge/intel_repack-feedstock/issues/80#issuecomment-2419973516). Yes, libfabric definitely shouldn't be bundled, but I haven't had the energy to tackle that myself. Great that you're taking the lead on that, and feel free to ping me for review in your PR to staged-recipes.

> remove the configure option `--enable-mca-dso` and this way the MPI library will will link to everything needed.

Is that true even with the cuda stuff? That bit still actually needs to be optional.

**Comment by dalcinl** [comment]
> Is that true even with the cuda stuff? That bit still actually needs to be optional.

Open MPI is still using `dlopen("libcuda.so")`, so I guess we can still have CUDA optional. 
I fired up a PR, I think we will take note if my guess proves wrong.

**Comment by minrk** [comment]
It is apparently now the _default_ behavior of openmpi 5 to build only cuda components as DSOs, which is exactly what we want, even if the openmpi docs don't reflect that.
