### ISSUE TITLE
Allow extra configuration arguments 

### ISSUE THREAD

**Issue by cjnolet** [conda-forge/openmpi-feedstock#42]
It would be nice if extra configuration arguments could be specified somehow. For instance, if we could specify “—with-cuda —with-ucx” so that a CUDA-aware MPI could be built.

**Comment by jakirkham** [comment]
FWIW have put an initial UCX package forward in PR ( https://github.com/conda-forge/staged-recipes/pull/9162 ), which should help here. This still doesn't handle some things that we would like it to, but it is a good foundation for adding that functionality.

**Comment by jakirkham** [comment]
It's probably worth looking at this more closely as we now have a UCX package and are able to perform GPU builds. Thoughts on this @conda-forge/openmpi ?

**Comment by jakirkham** [comment]
@minrk, do you have thoughts here? Happy to do a PR if this is reasonable. 🙂

**Comment by minrk** [comment]
Seems totally reasonable. Happy to have variants if they are useful.

**Comment by jakirkham** [comment]
Thanks Min. I'll work on a PR so we can discuss further.

**Comment by cjnolet** [comment]
This will be great! Currently, we have an MPI communicator implementation to run our automated GTests on RAPIDS cuML but it needs to be disabled by default because the users need to install CUDA-aware manually.

**Comment by leofang** [comment]
@cjnolet @jakirkham Do you happen to have a work in progress here? If not, I might be able to find some time and try enabling a GPU build. I just had an offline discussion with @dalcinl today, and then found this issue matching exactly what I intended to do! 

Context: We will make an official release of mpi4py soon, with the support of `__cuda_array_interface__` included (it was previously considered experimental and only available on master). So, it seems natural to me if we could build a CUDA variant for the Open MPI package, on which the updated mpi4py can then depend.

But, with some quick digging I found that neither OMPI nor mpi4py links to CUDA runtime (on conda-forge it'd be contained in `cudatoolkit` I think). The linking to CUDA is [done on the OMPI side at runtime via dlopen](https://github.com/open-mpi/ompi/blob/d14d8ad30d86f6650cb6c6384ddef304d408ff15/opal/mca/common/cuda/common_cuda.c#L309) (I suppose), and mpi4py doesn't care at all. So, @dalcinl suggested -- I hope I understood him correctly -- we take this route:
- instead of setting up either an output variant or a conditional flag `"nocuda`" in `conda_build_config.yaml`, we just enable the CUDA build by default for OMPI (adding `--with-cuda` in the build script and `{{ compiler("cuda") }}` in the `build` section of the recipe)
- but, in the recipe we do not specify `cudatoolkit` in the `run` section, so the package can still be used in envs without GPU
- in mpi4py's recipe, we make no change. 

Expected effect: If a user only installs `openmpi` + `mpi4py`, it'd work without CUDA awareness (unless it's running on a system with CUDA configured outside conda's control, which is beyond our reach and always a headache for any GPU libraries in conda); if a user installs `openmpi` + `mpi4py` + `cudatoolkit`, then the CUDA-awareness will kick in silently. What do you think, @conda-forge/openmpi?

Not sure about the UCX part. I built it myself a while ago, but I am not sure how its conda package works, so most likely will have to work with @cjnolet and @jakirkham on this.

**Comment by dalcinl** [comment]
@leofang A minor issue is to make sure that openmpi continues running (silently, without even a warning!) if the dlopening of the CUDA-aware plugin fails out of a missing CUDA runtime. And I said without a warning, because otherwise it would be really annoying to end users of the openmpi package not using CUDA.

**Comment by leofang** [comment]
> A minor issue is to make sure that openmpi continues running (silently, without even a warning!) if the dlopening of the CUDA-aware plugin fails out of a missing CUDA runtime. 

Looks like we need to find a way to turn off this MCA: https://github.com/open-mpi/ompi/blob/4944508603f26c7881696315bd35eda64a86130c/opal/runtime/opal_params.c#L260-L265 I'll look into it.

**Comment by leofang** [comment]
I suppose the scenario @dalcinl described is exactly this one? open-mpi/ompi#6896 It seems that `--mca opal_warn_on_missing_libcuda 0` can turn the warning off, but how do I set this during build time so that it's off by default for our users?

**Comment by dalcinl** [comment]
OK, from the Open MPI side, the warning makes sense to be on by default. From our side, I guess we can set the MCA parameter in `$PREFIX/etc/openmpi-mca-params.conf`, ie, adding something like this in the recipe build script

```
echo opal_warn_on_missing_libcuda = 0 >> $PREFIX/etc/openmpi-mca-params.conf
```

**Comment by jsquyres** [comment]
@dalcinl is exactly right.  This use case is one of the reasons that that file exists.

**Comment by jakirkham** [comment]
Thanks all for jumping in here. This work is greatly appreciated! 😄

It looks like you already got something working quickly, @leofang. Very impressive! Made a couple minor comments on your PR ( https://github.com/conda-forge/openmpi-feedstock/pull/54 ). Though please let us know if there is anything else you need to move this forward 😉

**Comment by jakirkham** [comment]
@jsquyres, if you are around, we could use your help understand OpenMPI linkage a bit. Please see [Leo's comment]( https://github.com/conda-forge/openmpi-feedstock/pull/54#discussion_r369818884 ) for context 🙂

**Comment by dalcinl** [comment]
@jakirkham It is all based on `dlopen()` and `dlsym()` https://github.com/open-mpi/ompi/blob/master/opal/mca/common/cuda/common_cuda.c#L319

@leofang Could you run `ldd` on the Open MPI's CUDA plugin to confirm that it is not linked against `libcuda.so.*`?

**Comment by leofang** [comment]
> Could you run `ldd` on the Open MPI's CUDA plugin to confirm that it is not linked against `libcuda.so.*`?

I did, and it's not, which was why I proposed making CUDA enabled by default. However, I want to be a bit conservative, as I am not sure whether or not during compile time Open MPI would detect the CUDA version it is built against with some macros and select different code paths for its CUDA plugins.

**Comment by dalcinl** [comment]
> I am not sure whether or not during compile time Open MPI would detect the CUDA version it is built against and select different code paths for its CUDA plugins.

Damn it! https://github.com/open-mpi/ompi/blob/master/opal/mca/common/cuda/common_cuda.c#L102-L111

**Comment by leofang** [comment]
> Damn it! https://github.com/open-mpi/ompi/blob/master/opal/mca/common/cuda/common_cuda.c#L102-L111

That part I am not worried. I guess it's for legacy CUDA. For CUDA 9.2+ as we have on CF, based on this file I think all CUDA flags `OPAL_CUDA_*` are set to 1?
https://github.com/open-mpi/ompi/blob/master/config/opal_check_cuda.m4

**Comment by jsquyres** [comment]
Er... I'm getting a little lost in the conversation between here and #54.  What question do you have / need answered about Open MPI linkage?

**Comment by leofang** [comment]
@jsquyres Thanks very much for your incredibly helpful comments in #54, Jeff! I think I gathered almost all I need to know except for this: Does the CUDA version (on CF we have 9.2, 10.0, 10.1 & 10.2) matter at compile time when building `openmpi` with `--with-cuda` flag? If it doesn't, I can simplify #54 quite a bit by building `openmpi` using, say, 9.2 and making it workable with any version of `cudatoolkit` we have.

**Comment by jsquyres** [comment]
It looks like there is a small number of `configure`-time decisions, which is... weird... to me.  I'll ask @Akshay-Venkatesh why this is on the Open MPI side (i.e., if we're `dlopen()`'ing, it would seem like at least some of those decisions should be made at `dlopen()` time, not `configure` time).

But I'll also wager that the things it is checking for at `configure` time is also fairly old CUDA functionality.  I wasn't responsible for the CUDA stuff in Open MPI at all, but it was done a while ago.  I don't know how that compares to the timeline of availability of CUDA 9.2 and 10.x, though, so you might want to check.

You can check thusly:

1. Compile with the oldest CUDA you care about (e.g., 9.2).  Grep for "OPAL_CUDA" in `opal/include/opal_config.h`.
2. Then compare with the newest CUDA you care about (e.g., 10.2).  Grep for "OPAL_CUDA" in `opal/include/opal_config.h`.
3. Compare the two sets of values.
    * If they're they same, huzzah!  You should be good -- i.e., the things Open MPI cares about are the same between the oldest and newest versions of CUDA that you care about.
    * If they're not the same, ...let's keep talking / figure something out here.

**Comment by jakirkham** [comment]
Looking at the comments it seems if we have CUDA>=7.0 we should be fine, but I'll wait for someone more familiar with the code to confirm that.

**Comment by leofang** [comment]
> Looking at the comments it seems if we have CUDA>=7.0 we should be fine

Yes, I think so too, based on inspection of the file `opal_check_cuda.m4`:

> For CUDA 9.2+ as we have on CF, based on this file I think all CUDA flags `OPAL_CUDA_*` are set to 1?
> https://github.com/open-mpi/ompi/blob/master/config/opal_check_cuda.m4

I'll check Jeff's suggestion (https://github.com/conda-forge/openmpi-feedstock/issues/42#issuecomment-577880633) later today, but most likely we're good.

**Comment by jakirkham** [comment]
Sounds good. Please let us know how it goes 🙂

**Comment by leofang** [comment]
Checked with CUDA 9.2 and 10.0. All macros `OPAL_CUDA_*` are set to `1`. I think we're good!

**Comment by leofang** [comment]
***Update:*** CUDA awareness is turned on by default in #54. Thanks so much to @jsquyres @dalcinl @jakirkham for your comments and help! This issue should remain open, though, until the UCX support is addressed.

**Comment by jakirkham** [comment]
Thanks for driving that forward Leo! 😄
